// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArzJoIglGRDU2GZLOH5Umo34KGC4BBgKc',
    appId: '1:342964184241:web:74b6aba809fc43d428ae90',
    messagingSenderId: '342964184241',
    projectId: 'fireflutter-518a5',
    authDomain: 'fireflutter-518a5.firebaseapp.com',
    storageBucket: 'fireflutter-518a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTjo9IAcxo7cp8k5xHxWauBoGHJXvPsw',
    appId: '1:342964184241:android:f84ce0dcbb62897828ae90',
    messagingSenderId: '342964184241',
    projectId: 'fireflutter-518a5',
    storageBucket: 'fireflutter-518a5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArzJoIglGRDU2GZLOH5Umo34KGC4BBgKc',
    appId: '1:342964184241:web:70846ac92f5fae4128ae90',
    messagingSenderId: '342964184241',
    projectId: 'fireflutter-518a5',
    authDomain: 'fireflutter-518a5.firebaseapp.com',
    storageBucket: 'fireflutter-518a5.appspot.com',
  );
}
